version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cassandra:
    image: cassandra:3

  spark-runner:
    image: bde2020/spark-scala-template
    environment:
      ENABLE_INIT_DAEMON: "false"
    depends_on:
      - cassandra
      - kafka
    command: sleep 2592000
    volumes:
      - "./src/sparkstreaming:/app"

  spark-runner-producer:
    image: bde2020/spark-scala-template
    environment:
      ENABLE_INIT_DAEMON: "false"
    depends_on:
      - cassandra
      - kafka
    command: sleep 2592000
    volumes:
      - "./src/generator:/app"


